controllers/TriggerController.php
<?php
namespace app\controllers;

use app\src\entities\access\AccessRole;
use app\src\entities\place\Club;
use app\src\entities\trigger\Trigger;
use app\src\entities\trigger\TriggerSearch;
use app\src\entities\user\Position;
use app\src\entities\user\User;
use app\src\library\AccessChecker;
use app\src\library\BaseController;
use app\src\service\TriggerService;
use yii\helpers\ArrayHelper;

class TriggerController extends BaseController
{
    public function actionIndex()
    {
        $triggerSearch = new TriggerSearch();
        $params = $this->getParams();

        $dataProvider = $triggerSearch->getSearchDataProvider($params);

        $this->appendEntryPoint('listing');

        return $this->render('index', [
            'searchModel' => $triggerSearch,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView()
    {
        $triggerId = (int) $this->getParam('id');

        $trigger = Trigger::findOne($triggerId);

        $this->appendEntryPoint('view');

        return $this->render('view', [
            'trigger' => $trigger,
            'receivers' => Trigger::getUsersByTrigger($trigger),
        ]);
    }

    /**
     * @return string|\yii\web\Response
     * @throws \Exception
     */
    public function actionCreate()
    {
        $attributes = $this->getParams();

        if (\Yii::$app->request->isPost) {

            $triggerService = new TriggerService();
            $triggerService->createByData($attributes);
            return $this->redirect('/trigger/index');
        }

        if (AccessChecker::isSuperAdmin()) {
            $users = User::getAll();
            $clubs = Club::getAll();
            $clubsIds = ArrayHelper::map($clubs, 'id', 'id');
        } else {
            $clubs = Club::getClubsByUserId(\Yii::$app->user->getId());
            $clubsIds = ArrayHelper::map($clubs, 'id', 'id');

            $customers = User::getCustomers($clubsIds);
            $staff = User::getStaff($clubsIds);
            $users = array_merge($customers, $staff);
        }

        $trigger = new Trigger();
        $trigger->clubsIds = $clubsIds;

        $this->appendEntryPoint();

        return $this->render('create', [
            'trigger' => $trigger,
            'clubs' => $clubs,

            'positions' => Position::getAll(),
            'roles' => AccessRole::getAll(),
            'users' => $users,
        ]);
    }

    /**
     * @return string|\yii\web\Response
     * @throws \Exception
     */
    public function actionUpdate()
    {
        $attributes = $this->getParams();
        $triggerId = (int) $this->getParam('id');

        if (\Yii::$app->request->isPost) {

            $triggerService = new TriggerService();
            $triggerService->updateByData($triggerId, $attributes);
            return $this->redirect('/trigger/index');
        }

        $trigger = Trigger::findOne($triggerId);

        if (AccessChecker::isSuperAdmin()) {
            $users = User::getAll();
            $clubs = Club::getAll();
        } else {
            $clubs = Club::getClubsByUserId(\Yii::$app->user->getId());
            $clubsIds = ArrayHelper::map($clubs, 'id', 'id');

            $customers = User::getCustomers($clubsIds);
            $staff = User::getStaff($clubsIds);
            $users = array_merge($customers, $staff);
        }

        $this->appendEntryPoint('trigger.create');

        return $this->render('create', [
            'trigger' => $trigger,
            'clubs' => $clubs,

            'positions' => Position::getAll(),
            'roles' => AccessRole::getAll(),
            'users' => $users,

            'receivers' => Trigger::getUsersByTrigger($trigger),
        ]);
    }

    public function actionDelete($id)
    {
        $isAjax = $this->getParam('isAjax');

        Trigger::deleteAll([
            'id' => $id,
        ]);

        if ($isAjax) {
            return $this->responseListing(new TriggerSearch(), '/trigger/index');
        }

        return $this->redirect('/trigger/index');
    }

    public function actionGetReceiversList()
    {
        $triggerId = (int) $this->getParam('id');
        $trigger = Trigger::findOne($triggerId);

        $receiversList = $this->renderAjax('/trigger/partial/receivers', [
            'receivers' => Trigger::getUsersByTrigger($trigger),
        ]);

        return $this->responseJson([
            'html' => $receiversList,
        ]);
    }
}

views/trigger/create.php
<?php

use app\src\entities\trigger\Trigger;
use app\src\entities\user\User;
use app\src\widget\UFActiveForm;
use yii\web\View;
use app\src\entities\translate\Language;
use yii\helpers\Html;

/* @var View $this */
/* @var Trigger $trigger */
/* @var User[] $receivers */

$this->title = $trigger->isNewRecord ? Yii::t('app', 'Trigger Create') : Yii::t('app', 'Trigger Update');

$this->params['breadcrumbs'][] = ['label' => \Yii::t('app', 'Trigger'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$receivers = $receivers ?? [];
?>

<div class="row">
    <div class="col-lg-8">
        <div class="uf-form-create">
            <div class="nav-tabs-form js-nav-tabs">
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#main" data-toggle="tab" aria-expanded="false"><?= $this->title ?></a>
                    </li>
                    <li>
                        <a href="#translations" data-toggle="tab"
                           aria-expanded="false"><?= \Yii::t('app', 'Translations') ?></a>
                    </li>
                </ul>

                <?php $form = UFActiveForm::begin([
                    'id' => 'trigger-update-form',
                    'options' => ['class' => 'js-trigger-form trigger-update-form'],
                    'fieldConfig' => [
                        'template' => '<div class="col-sm-2 col-xs-12 p-0">{label}</div><div class="col-sm-10 col-xs-12 p-0">{input}{error}{hint}</div>',
                    ]
                ]) ?>

                <div class="box-body">

                    <div class="tab-content js-edit-place-container">

                        <div class="tab-pane active" id="main">
                            <?= $this->render('/trigger/partial/trigger-form.php', $_params_ + ['form' => $form]) ?>
                        </div>
                        <div class="tab-pane" id="translations">
                            <?= $this->render('/trigger/partial/_translations', [
                                'model' => $trigger,
                                'languages' => Language::getList(),
                            ]) ?>
                        </div>

                        <div class="nav-tabs-buttons">

                            <?= Html::submitButton(
                                $trigger->isNewRecord
                                    ? \Yii::t('app', 'Create Trigger')
                                    : \Yii::t('app', 'Update Trigger'),
                                [
                                    'class' => 'js-button-process btn btn-success float-right',
                                    'value' => 'save',
                                ]
                            ) ?>

                        </div>
                    </div>
                </div>
                <?php UFActiveForm::end() ?>
                <?php if (!empty($receivers)): ?>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="js-receivers-form receivers-form box uf-form-create">

            <div class="box-header">
                <h3 class="box-title"><?= Yii::t('app', 'Receivers by AF') ?></h3>
            </div>

            <div class="box-body">
                <?= $this->render('/trigger/partial/receivers.php', $_params_) ?>
            </div>
        </div>
    </div>
    <?php endif; ?>
</div>

views/trigger/index.php
<?php

use app\src\entities\access\AccessPermission;
use app\src\entities\trigger\Trigger;
use app\src\helpers\TriggerHelper;
use app\src\library\AccessChecker;
use yii\data\ActiveDataProvider;
use app\src\widget\UFGridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

/* @var View $this */
/* @var ActiveDataProvider $dataProvider */

$this->title = Yii::t('app', 'Trigger');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box uf-listing js-listing">

    <div class="box-header">
        <h3 class="box-title"><?= Yii::t('app', 'Trigger List') ?></h3>

        <?php if (AccessChecker::hasControllerAccess('trigger', AccessPermission::TYPE_CREATE)) {
            echo Html::a(Yii::t('app', 'Create Trigger'), ['trigger/create'], ['class' => 'btn btn-sm btn-success float-right']);
        } ?>

    </div>

    <div class="box-body">
        <?= $this->render('/_templates/confirm-dialog.php') ?>

        <?= UFGridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                [
                    'attribute' => 'id',
                    'label' => Yii::t('app', 'ID')
                ],
                [
                    'attribute' => 'name',
                    'sortLinkOptions' => ['class' => 'sorting'],
                    'label' => Yii::t('app', 'Name'),
                ],
                [
                    'attribute' => 'types',
                    'value' => function ($model) {
                        return TriggerHelper::getTypeLabels($model['types']);
                    },
                    'sortLinkOptions' => ['class' => 'sorting'],
                    'label' => Yii::t('app', 'Type'),
                ],
                [
                    'attribute' => 'event',
                    'value' => function ($model) {
                        return Trigger::EVENT_LABELS[$model['event']];
                    },
                    'sortLinkOptions' => ['class' => 'sorting'],
                    'label' => Yii::t('app', 'Event'),
                ],
                [
                    'attribute' => 'template',
                    'label' => Yii::t('app', 'Template')
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'buttons' => [
                        'view' => function ($url) {
                            return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url);
                        },
                        'update' => function ($url, $model) {
                            if (!AccessChecker::hasPermission('trigger.update')) {
                                return '';
                            }
                            $title = htmlspecialchars(Yii::t('app', 'Update "') . $model['name'] . '"');
                            return Html::a('<span class="glyphicon glyphicon-pencil"
                                data-title="' . $title . '"></span>', $url);
                        },
                        'delete' => function ($url, $model) {
                            if (!AccessChecker::hasPermission('trigger.delete')) {
                                return '';
                            }
                            $destination = TriggerHelper::getTypeLabels($model['types']);
                            $title = htmlspecialchars(Yii::t('app', 'Delete ') . $destination);
                            $message = htmlspecialchars(Yii::t('app', 'Do you really want to delete "') . $model['name'] . Yii::t('app',  '" trigger?'));

                            return Html::tag('span', '', [
                                'class' => 'js-delete uf-listing-button uf-listing-button-delete glyphicon glyphicon-trash',
                                'data-url' => $url,
                                'data-title' => $title,
                                'data-confirm-message' => $message,
                                'data-notification-message' => [
                                    'success' => Yii::t('app', 'Trigger have been successfully deleted.'),
                                    'error' => Yii::t('app', 'Trigger have\'t been deleted.'),
                                ],
                            ]);
                        },
                    ],
                    'urlCreator' => function ($action, $model) {
                        switch ($action) {
                            case 'view': return Url::to(['trigger/view', 'id' => $model['id']]);
                            case 'update': return Url::to(['trigger/update', 'id' => $model['id']]);
                            case 'delete': return Url::to(['trigger/delete', 'id' => $model['id']]);
                            default: return Url::to(['trigger/view', 'id' => $model['id']]);
                        }
                    }
                ],
            ],
        ]); ?>
    </div>
</div>

views/trigger/partial/_translations.php
<?php

use app\src\entities\translate\Language;
use yii\helpers\Html;
use yii\jui\Accordion;
use app\src\widget\UFActiveForm;

/* @var Language[] $languages */

$items = [];
$form = UFActiveForm::begin(['id' => 'club-update-info-form', 'options' => ['class' => 'js-club-update-info-form']]);
foreach ($languages as $languageId => $languageName) {
    $translation = $model->translations[$languageId];

    $header = Html::tag('div', '', ['class' => 'pull-left flag flag-' . $languageId]) . '&nbsp; ' . $languageName;

    $content = $form->field($translation, '[' . $languageId . ']title')->label(\Yii::t('app', 'Title'))
        . $form->field($translation, '[' . $languageId . ']template', [
            'options' => ['class' => 'row js-template-translate mt-3'],
            'template' => '<div class="col-sm-3">{label}</div>
                           <div class="col-sm-9"><div class="js-template-translate-hint event-codes"></div>{input}{error}</div>',
        ])->label(\Yii::t('app', 'Template'))->textarea(['rows' => 4]);

    $items[] = [
        'header' => $header,
        'content' => $content,
    ];
}
?>
    <div class="box-body">
        <div class="translation-accordion">
        <?= Accordion::widget([
            'items' => $items,
            'clientOptions' => [
                'heightStyle' => 'content',
                'animate' => ['duration' => 300],
                'collapsible' => count($languages) > 1,
                'active' => false,
            ],
            'headerOptions' => ['tag' => 'div'],
        ]); ?>
        </div>
    </div>
<?php UFActiveForm::end() ?>

views/trigger/partial/receivers.php
<?php

use app\src\entities\trigger\Trigger;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;

/* @var [] $receivers */
/* @var Trigger $trigger */
?>

<div class="uf-view">
    <?php
    $receiversNames = ArrayHelper::map($receivers, 'id', 'name_label');

    echo Select2::widget([
        'name' => 'receivers',
        'data' => $receiversNames,
        'value' => array_keys($receiversNames),
        'options' => [
            'disabled' => true,
            'id' => 'trigger_user_id',
            'multiple' => true,
            'prompt' => '',
        ],
    ]);
    ?>
</div>

views/trigger/partial/trigger-form.php
<?php

use app\src\entities\access\AccessRole;
use app\src\entities\place\Club;
use app\src\entities\trigger\Trigger;
use app\src\entities\user\Position;
use app\src\entities\user\User;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\web\View;
use yii\jui\Accordion;
use \app\src\helpers\TriggerHelper;
use \kartik\sortinput\SortableInput;
use \app\src\entities\trigger\TriggerType;

/* @var View $this */
/* @var Trigger $trigger */
/* @var Club[] $clubs */
/* @var Position[] $positions */
/* @var AccessRole[] $roles */
/* @var User[] $users */
/* @var User[] $receivers */

$triggerTypes = $trigger->types;
$trigger->types = null;
$senderEmailClass = TriggerHelper::isTriggerTypeEmailNotification($triggerTypes) ? '' : 'hide';
?>

<?= $form->field($trigger, 'name')->label(\Yii::t('app', 'Name')) ?>

<div class="form-group">

    <div class="col-lg-12 col-lg-offset-0 col-sm-10 col-sm-offset-2 p-0">
        <div class="form-group">

            <div class="col-lg-4 col-lg-offset-2 p-0">
                <div class="row">
                    <div class="col-lg-12">
                        <label><?= Yii::t('app', 'Picked Types') ?></label>
                    </div>
                </div>
                <?= $form->field($trigger, 'types', ['template' => '<div class="col-lg-12 col-xs-12 p-0">{input}{error}{hint}</div>'])
                    ->widget(SortableInput::class, [
                        'id' => 'trigger-type-connected',
                        'hideInput' => true,
                        'sortableOptions' => [
                            'connected' => true,
                        ],
                        'options' => [
                            'class' => 'form-control trigger-type-sortable-input js-trigger-type-sortable-input',
                            'readonly' => true,
                        ],
                        'items' => $trigger->getTypes()
                            ? TriggerHelper::getTypeTemplates($triggerTypes)
                            : TriggerHelper::getTypeTemplates([new TriggerType(['type' => Trigger::TYPE_MOBILE_NOTIFICATION])])
                    ])->label(false); ?>
                <?= '<div class="clearfix"></div>' ?>
            </div>

            <div class="col-lg-4 col-lg-offset-1 p-0">
                <div class="row">
                    <div class="col-lg-12">
                        <label><?= Yii::t('app', 'Available Types') ?></label>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 col-sm-12">
                        <?= SortableInput::widget([
                            'id' => 'trigger-type',
                            'name' => 'trigger-type',
                            'hideInput' => true,
                            'sortableOptions' => [
                                'connected' => true,
                            ],
                            'options' => ['class' => 'form-control trigger-type-sortable-input js-trigger-type-sortable-input-available', 'readonly' => true],
                            'items' => $trigger->isNewRecord ? TriggerHelper::getTypeTemplates() : TriggerHelper::getTypeTemplates($trigger->getTypes(), true)
                        ]); ?>
                    </div>
                </div>
            </div>

        </div>
        <small class="col-lg-10 col-lg-offset-2 p-0 mb-2 text-muted">
            <?= Yii::t('app', 'messages will be sent in the specified order') ?>
        </small>
    </div>
</div>

<?= $form->field($trigger, 'event')->widget(Select2::class, [
    'data' => Trigger::getTranslateEventLabels(),
    'options' => [
        'class' => 'js-event-select',
        'data-codes' => json_encode(Trigger::EVENT_CODES),
        'data-default-codes' => json_encode(Trigger::DEFAULT_CODES),
        'multiple' => false,
        'prompt' => \Yii::t('app', 'select trigger'),
    ],
    'pluginOptions' => [
        'tags' => true,
        'tokenSeparators' => [','],
    ],
])->label(\Yii::t('app', 'Event')) ?>

<?= $form->field($trigger, 'clubsIds', ['options' => ['class' => 'hide']])->widget(Select2::class, [
    'data' => ArrayHelper::map($clubs, 'id', 'name'),
    'options' => [
        'multiple' => true,
        'prompt' => \Yii::t('app', 'select clubs'),
    ],
    'pluginOptions' => [
        'tags' => true,
        'tokenSeparators' => [','],
    ],
])->label(\Yii::t('app', 'Clubs')) ?>

<?= $form->field($trigger, 'title')->label(\Yii::t('app', 'Title')) ?>

<?php $header = Html::tag('div', '', ['class' => 'pull-left trigger-advanced-filters']) . '&nbsp; ' . Yii::t('app', 'Advanced Filters') . ': ';

$content = $form->field($trigger, 'advanced_filters')->checkbox(['class' => 'js-checkbox-advanced_filters']) . '<div class="js-advanced_filters-accordion">'
    . $form->field($trigger, 'sender_email', ['options' => ['class' => 'js-sender-email ' . $senderEmailClass]])->label(\Yii::t('app', 'Sender email'))
    . $form->field($trigger, 'places')->widget(Select2::class, [
        'data' => ArrayHelper::map($clubs, 'id', 'name'),
        'options' => [
            'multiple' => true,
            'prompt' => \Yii::t('app', 'select clubs'),
        ],
        'pluginOptions' => [
            'tags' => true,
            'tokenSeparators' => [','],
        ],
    ])->label(\Yii::t('app', 'Clubs'))

    . $form->field($trigger, 'to_user_type')->widget(Select2::class, [
        'data' => [
            'to_staff' => Yii::t('app', 'to staff'),
            'to_customers' => Yii::t('app', 'to customers'),
        ],
        'options' => [
            'multiple' => true,
            'prompt' => \Yii::t('app', 'select types'),
        ],
        'pluginOptions' => [
            'tags' => true,
            'tokenSeparators' => [','],
        ],
    ])->label(\Yii::t('app', 'User type'))

    . $form->field($trigger, 'positions')->widget(Select2::class, [
        'data' => ArrayHelper::map($positions, 'id', 'name'),
        'options' => [
            'multiple' => true,
            'prompt' => \Yii::t('app', 'select positions'),
        ],
        'pluginOptions' => [
            'tags' => true,
            'tokenSeparators' => [','],
        ],
    ])->label(\Yii::t('app', 'Positions'))

    . $form->field($trigger, 'roles')->widget(Select2::class, [
        'data' => ArrayHelper::map($roles, 'id', 'name'),
        'options' => [
            'multiple' => true,
            'prompt' => \Yii::t('app', 'select roles'),
        ],
        'pluginOptions' => [
            'tags' => true,
            'tokenSeparators' => [','],
        ],
    ])->label(\Yii::t('app', 'Roles'))

    . $form->field($trigger, 'users')->widget(Select2::class, [
        'data' => ArrayHelper::map($users, 'id', 'username'),
        'options' => [
            'multiple' => true,
            'prompt' => \Yii::t('app', 'select users'),
        ],
        'pluginOptions' => [
            'tags' => true,
            'tokenSeparators' => [','],
        ],
    ])->label(\Yii::t('app', 'Users')) . '</div>';

$items[] = [
    'header' => $header,
    'content' => $content,
]; ?>

<?= $form->field($trigger, 'template', [
    'options' => ['class' => 'form-group js-template mt-3'],
    'template' => '<div class="col-sm-2 p-0">{label}</div>
                           <div class="col-sm-10 p-0"><div class="js-template-hint event-codes"></div>{input}{error}</div>',
])->textarea(['rows' => 5])
    ->label(\Yii::t('app', 'Template')) ?>

<div class="trigger-advanced-filters">
<?= Accordion::widget([
    'items' => $items,
    'clientOptions' => [
        'heightStyle' => 'content',
        'animate' => ['duration' => 300],
        'collapsible' => true,
        'active' => false,
    ],
    'headerOptions' => ['tag' => 'div'],
]); ?>
</div>

views/trigger/view.php
<?php

use app\src\entities\trigger\Trigger;
use app\src\entities\user\User;
use app\src\helpers\TriggerHelper;
use app\src\library\AccessChecker;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\web\View;

/* @var View $this */
/* @var Trigger $trigger */
/* @var User[] $receivers */

$this->title = Yii::t('app', 'Trigger View');
$this->params['breadcrumbs'][] = ['label' => \Yii::t('app', 'Trigger'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$receivers = $receivers ?? [];
?>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-8">
            <div class="box uf-view js-view">

                <div class="box-header">
                    <h3 class="box-title"><?= $trigger->name ?></h3>>
                </div>

                <div class="box-body">

                    <?= $this->render('/_templates/confirm-dialog.php') ?>
                    <div class="row">
                        <div class="col-sm-3 col-md-2"><strong><?= Yii::t('app', 'Types') ?></strong></div>
                        <div class="col-sm-9 col-md-10"><?= TriggerHelper::getTypeLabels($trigger['types']); ?></div>
                    </div>

                    <div class="row">
                        <div class="col-sm-3 col-md-2"><strong><?= Yii::t('app', 'Event') ?></strong></div>
                        <div class="col-sm-9 col-md-10"><?= Trigger::EVENT_LABELS[$trigger->event] ?></div>
                    </div>

                    <div class="row">
                        <div class="col-sm-3 col-md-2"><strong><?= Yii::t('app', 'Clubs') ?></strong></div>
                        <div class="col-sm-9 col-md-10">
                                <?= Select2::widget([
                                    'name' => 'clubs',
                                    'data' => ArrayHelper::map($trigger->getPlaces(), 'id', 'name'),
                                    'value' => ArrayHelper::map($trigger->getPlaces(), 'id', 'id'),
                                    'options' => [
                                        'disabled' => true,
                                        'id' => 'trigger_club_ids',
                                        'multiple' => true,
                                        'prompt' => '',
                                    ],
                                ]);?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-3 col-md-2"><strong><?= Yii::t('app', 'User Type') ?></strong></div>
                        <div class="col-sm-9 col-md-10">
                                <?= Select2::widget([
                                    'name' => 'user type',
                                    'data' => $trigger->to_user_type,
                                    'value' => array_keys($trigger->to_user_type),
                                    'options' => [
                                        'disabled' => true,
                                        'id' => 'trigger_user_type',
                                        'multiple' => true,
                                        'prompt' => '',
                                    ],
                                ]);?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-3 col-md-2"><strong><?= Yii::t('app', 'Positions') ?></strong></div>
                        <div class="col-sm-9 col-md-10">
                                <?= Select2::widget([
                                    'name' => 'positions',
                                    'data' => ArrayHelper::map($trigger->getPositions(), 'id', 'name'),
                                    'value' => ArrayHelper::map($trigger->getPositions(), 'id', 'id'),
                                    'options' => [
                                        'disabled' => true,
                                        'id' => 'trigger_position_ids',
                                        'multiple' => true,
                                        'prompt' => '',
                                    ],
                                ]); ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-3 col-md-2"><strong><?= Yii::t('app', 'Roles') ?></strong></div>
                        <div class="col-sm-9 col-md-10">
                                <?= Select2::widget([
                                    'name' => 'roles',
                                    'data' => ArrayHelper::map($trigger->getRoles(), 'id', 'name'),
                                    'value' => ArrayHelper::map($trigger->getRoles(), 'id', 'id'),
                                    'options' => [
                                        'disabled' => true,
                                        'id' => 'trigger_role_ids',
                                        'multiple' => true,
                                        'prompt' => '',
                                    ],
                                ]); ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-3 col-md-2"><strong><?= Yii::t('app', 'Users') ?></strong></div>
                        <div class="col-sm-9 col-md-10">
                                <?= Select2::widget([
                                    'name' => 'users',
                                    'data' => ArrayHelper::map($trigger->getUsers(), 'id', 'username'),
                                    'value' => ArrayHelper::map($trigger->getUsers(), 'id', 'id'),
                                    'options' => [
                                        'disabled' => true,
                                        'id' => 'trigger_user_ids',
                                        'multiple' => true,
                                        'prompt' => '',
                                    ],
                                ]); ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-3 col-md-2"><strong><?= Yii::t('app', 'Template') ?></strong></div>
                        <div class="col-sm-9 col-md-10"><?= $trigger->template ?></div>
                    </div>

                    <div class="row">
                        <div class="col-sm-3 col-md-2"><strong><?= Yii::t('app', 'Receivers') ?></strong></div>
                        <div class="col-sm-9 col-md-10"><?= $this->render('/trigger/partial/receivers.php', $_params_) ?></div>
                    </div>

                    <div class="row">
                        <div class="col-xs-12">
                            <?= Html::a(\Yii::t('app', 'Back'), ['/trigger/index'],
                                [
                                    'class' => 'btn btn-success float-left mr-3',
                                    'value' => 'save',
                                ]
                            ) ?>

                            <?php if (AccessChecker::hasPermission('trigger.update')) {
                                echo Html::a(\Yii::t('app', 'Edit'), ['/trigger/update?id=' . $trigger->id],
                                    [
                                        'class' => 'btn btn-success float-left',
                                        'value' => 'save',
                                    ]
                                );} ?>

                            <?php if (AccessChecker::hasPermission('trigger.delete')) {
                                $title = htmlspecialchars(Yii::t('app', 'Delete club'));
                                $message = htmlspecialchars(Yii::t('app', 'Do you really want to delete "') . $trigger['name'] . Yii::t('app', '" trigger?'));
                                echo Html::tag('span', \Yii::t('app', 'Delete'), [
                                    'class' => 'js-delete uf-view-button uf-view-button-delete btn btn-danger float-right',
                                    'data-url' => '/trigger/delete?id=' . $trigger->id,
                                    'data-title' => $title,
                                    'data-message' => $message,
                                ]);}?>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
</div>